#if defined _inc_config
    #undef _inc_config
#endif
#if defined _VSAO_FFAconfig_
    #endinput
#endif
#define _VSAO_FFAconfig_

//---------------------------------------------------------

#define FFA_NAME 			"Free For All"
#define FFA_SHORTNAME		"FFA"
#define FFA_MOD_TYPE		MOD_TYPE_FREE
#define FFA_CLASS			NO_CLASS
#define FFA_MAX_SCORE		1500

#define FFA_AUTHOR			"C_far"

//---------------------------------------------------------

#define FFA_KILLED_SCORE	100
