#if defined _inc_config
    #undef _inc_config
#endif
#if defined _VSAO_RWconfig_
    #endinput
#endif
#define _VSAO_RWconfig_

//---------------------------------------------------------

#define RW_NAME 			"Rocket War"
#define RW_SHORTNAME		"RW"
#define RW_MOD_TYPE			MOD_TYPE_FREE
#define RW_CLASS			CLASS_ROCKETEER
#define RW_MAX_SCORE		1000

#define RW_AUTHOR			"C_far"

//---------------------------------------------------------

#define RW_KILLED_SCORE	100
