#if defined _inc_config
    #undef _inc_config
#endif
#if defined _VSAO_SWconfig_
    #endinput
#endif
#define _VSAO_SWconfig_

//---------------------------------------------------------

#define SW_NAME 			"Sniper War"
#define SW_SHORTNAME		"SW"
#define SW_MOD_TYPE			MOD_TYPE_FREE
#define SW_CLASS			CLASS_HUNTER
#define SW_MAX_SCORE		1000

#define SW_AUTHOR			"C_far"

//---------------------------------------------------------

#define SW_KILLED_SCORE	100
